Work for #2090 - added fonts
surveyjs/survey-creator pull request #2114
Opened 2021-10-25 10:38 UTC by ST-1580

2021-11-16 09:00 UTC, tsv2013 requested changes
I believe we needn't load all these fonts. @novikov82 will explain how it should be.

2021-11-16 09:01 UTC, tsv2013 requested changes
Sorry for the late feedback. It hasn't be ready in my mind.

2021-11-18 10:08 UTC, ST-1580 commented
Firstly, see this PR: https://github.com/surveyjs/survey-library/pull/3626

2021-11-18 11:46 UTC, tsv2013 requested changes
We need to change fonts list

2021-11-18 11:46 UTC, tsv2013 commented on packages/survey-creator-core/src/variables.scss
> +$font-family: "Open Sans", "Roboto", sans-serif;
"Roboto" is non-standard. We need to use: "Helvetica Neue", Helvetica, Arial, sans-serif
After open sans

2021-11-18 12:57 UTC, tsv2013 approved these changes

2021-11-18 12:57 UTC, merged