fixed #2422 - click near item
surveyjs/survey-creator pull request #2555
Opened 2022-01-19 16:46 UTC by novikov82

fixed #2422

2022-01-19 17:35 UTC, dmitrykurmanov requested changes

2022-01-19 17:35 UTC, dmitrykurmanov commented on testCafe/designer/string-editor.ts
> +    .debug()
remove .debug :)

2022-01-20 06:42 UTC, novikov82 commented on testCafe/designer/string-editor.ts
> +    .debug()
https://github.com/surveyjs/survey-creator/pull/2555/commits/2e613b0de50b1062356c7f721f0a57ebf9ea26be

2022-01-20 09:37 UTC, dmitrykurmanov approved these changes

2022-01-20 09:38 UTC, merged